<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" /> <!-- definie l'encodage de la page -->
        <link rel="stylesheet" href="style.css" />  <!-- definie la page de css à aller recherhcer -->
        <title><?php echo $titre;?></title> <!-- affiche le titre de l'onglet dans le navigateur definie dans common.php -->
    </head>
    <body>
        <div id="bloc_page">
<?php
	//affiche le header
	include("header.php"); 
		
	//Affiche le contenu definie dans common.php
	echo '<section class="contenu">'.$out.'</section>'; 

	//affiche le footer
	include("footer.php"); 
?>
		</div>
	
	<script type="text/javascript"
		function verifjs_suppr() {
		return window.confirm('Êtes vous sûr de vouloir supprimer ?'); 
		}
	</script>
	<script type="text/javascript"> 
	<!-- 
	$(body).ready( function () { 
		// On cache les sous-menus 
		// sauf celui qui porte la classe "open_at_load" : 
		$("nav ul.subMenu:not('.open_at_load')").hide(); 
		// On selectionne tous les items de liste portant la classe "toggleSubMenu" 
	  
		// et on remplace l'element span qu'ils contiennent par un lien : 
		$("nav li.toggleSubMenu span").each( function () { 
			// On stocke le contenu du span : 
			var TexteSpan = $(this).text(); 
			$(this).replaceWith('<a href="" title="Afficher le sous-menu">' + TexteSpan + '<\/a>') ; 
		} ) ; 

		// On modifie l'evènement "click" sur les liens dans les items de liste 
		// qui portent la classe "toggleSubMenu" : 
		$("nav li.toggleSubMenu > a").click( function () { 
			// Si le sous-menu etait dejà ouvert, on le referme : 
			if ($(this).next("ul.subMenu:visible").length != 0) { 
				$(this).next("ul.subMenu").slideUp("normal", function () { $(this).parent().removeClass("open") } ); 
			} 
			// Si le sous-menu est cache, on ferme les autres et on l'affiche : 
			else { 
				$("nav ul.subMenu").slideUp("normal", function () { $(this).parent().removeClass("open") }); 
				$(this).next("ul.subMenu").slideDown("normal", function () { $(this).parent().addClass("open") } ); 
			} 
			// On empêche le navigateur de suivre le lien : 
			return false; 
		}); 

	} ) ; 
	
	function verifjs_suppr() {
		return window.confirm('Êtes vous sûr de vouloir supprimer ?'); 
		}
	</script>
	
	<script>
		<?php require_once ROOT_PATH.'/application/templates/script.js'; ?>
		<?php require_once ROOT_PATH.'/application/templates/inputInt.js'; ?>
	</script>

	
    </body>
</html>
